# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 951d72e212abf195b00bccefa1a77153e3fd24d6a43028b890dc885b3a99acce3ec8185fea3c9c734a061488dc2c906e77111a4e48d8b061439c2ee76fbe5d36

test:
  secret_key_base: 19ddeb1542bb9b4070c484acfdf44064f060a03f3205f453467b8e53fe74b5a1cc15167965a60adc69168753606b3602d65931ab54697b925ac388abb0390527

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
